spring:
  application:
    name: gateway-server-${server.port}
  datasource:
    url: jdbc:h2:./data/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
server:
  port: 8081

logging:
  level:
    root: info
    com:
      example: debug


axon:
  axonserver:

    servers: localhost:8124,localhost:8125
    enabled: false

  distributed:
    enabled: true
    spring-cloud:
      fallback-to-http-get: true
      fallback-url: /message-routing-information

      mode: rest

  serializer:
    general: xstream
    messages: xstream
    events: xstream





