version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - network1

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - 9092:9092
    networks:
      - network1

  kafka-rest:
    image: nodefluent/kafka-rest
    ports:
      - 8083:8083
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    environment:
      DEBUG: "*"
      KAFKA_REST_DEBUG: "all"
      KAFKA_REST_HTTP_PORT: 8083
      KAFKA_REST_CONSUMER_METADATA_BROKER_LIST: "kafka:9092"
      KAFKA_REST_PRODUCER_METADATA_BROKER_LIST: "kafka:9092"
    networks:
      - network1

  kafka-rest-ui:
    image: nodefluent/kafka-rest-ui
    ports:
      - 8000:8000
    links:
      - kafka-rest
    depends_on:
      - kafka-rest
    environment:
      DEBUG: "*"
      REACT_APP_KAFKA_REST_URL: "http://kafka-rest:8083/"
      REACT_APP_TIMEOUT: "3000"
      PROXY: "yes"
      BASIC_AUTH_USER: "admin"
      BASIC_AUTH_PASSWORD: "admin"
    networks:
      - network1


  eureka-server1:
    image: eureka
    container_name: eureka-server1
    hostname: eureka-server1
    networks:
      - eureka-net
    ports:
      - 8761:8761
    environment:
      - spring.profiles.active=node1

  eureka-server2:
    image: eureka
    container_name: eureka-server2
    hostname: eureka-server2
    networks:
      - eureka-net
    ports:
      - 8762:8762
    environment:
      - spring.profiles.active=node2

  eureka-server3:
    image: eureka
    container_name: eureka-server3
    hostname: eureka-server3
    networks:
      - eureka-net
    ports:
      - 8763:8763
    environment:
      - spring.profiles.active=node3

  app-server1:
    image: server
    container_name: app-server1
    hostname: app-server1
    networks:
      - eureka-net
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=node1

  app-server2:
    image: server
    container_name: app-server2
    hostname: app-server2
    networks:
      - eureka-net
    ports:
      - 8090:8090
    environment:
      - spring.profiles.active=node2

  gateway-server1:
    image: gateway
    container_name: gateway-server1
    hostname: gateway-server1
    networks:
      - eureka-net
    ports:
      - 8081:8081
    environment:
      - spring.profiles.active=node1

  gateway-server2:
    image: gateway
    container_name: gateway-server2
    hostname: gateway-server2
    networks:
      - eureka-net
    ports:
      - 8091:8091
    environment:
      - spring.profiles.active=node2
networks:
  network1:
  eureka-net:
    driver: bridge