spring:
  application:
    name: instruction
  datasource:
    url: jdbc:mysql://localhost:3306/axon?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  #④ 声明jpa相关配置，必须使用MySQL5InnoDBDialect声明数据库的存储引擎为InnoDB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    #show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

server:
  port: 8080

logging:
  level:
    root: info
    com:
      example: debug

axon:
  axonserver:
    enabled: false
#  eventhandling:
#    processors:
#      sub:
#        mode: subscribing
#        source: eventBus
#      track:
#        mode: tracking
#          source: eventBus
  distributed:
    enabled: true
    spring-cloud:
      fallback-to-http-get: true
      fallback-url: /message-routing-information
      mode: rest
      enable-ignore-listing: true
      enable-accept-all-commands: true
  serializer:
    general: xstream
    messages: xstream
    events: xstream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    metadata-map:
      instance-type: eda
    preferIpAddress: true
#axon:
#  axonserver:
#    enabled: false
#  distributed:
#    enabled: true
#    spring-cloud:
#      mode: rest
#      enable-ignore-listing: true
#      enable-accept-all-commands: true
##  serializer:
##    general: xstream
##    messages: xstream
##    events: xstream
#eureka:
#  instance:
#    metadata-map:
#      instance-type: eda
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30



## Required to enabled the DistributedCommandBus
#  axon.distributed.enabled=true
#  # Defines the CapabilityDiscoveryMode used. Defaults to REST
#  axon.distributed.spring-cloud.mode=rest
#  # Defines the endpoint used to retrieve member capabilities from. Defaults to "/member-capabilities"
#  axon.distributed.spring-cloud.rest-mode-url="/my-custom-endpoint"
#  # Defines whether the CapabilityDiscoveryMode should be decorated to ignore faulty ServiceInstances
#  axon.distributed.spring-cloud.enable-ignore-listing=true
#  # Defines whether the CapabilityDiscoveryMode should be decorated to accept all types of commands
#  axon.distributed.spring-cloud.enable-accept-all-commands=true
