spring:
  application:
    name: gateway-server
#  datasource:
#    url: jdbc:h2:./data/gateway/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/axon1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  #④ 声明jpa相关配置，必须使用MySQL5InnoDBDialect声明数据库的存储引擎为InnoDB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    #show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true


server:
  port: 8081

logging:
  level:
    root: info
    com:
      example: debug

axon:
  kafka:
    enable: false
    bootstrap-servers: localhost:9092
    client-id: gateway
    default-topic: local.event2
    properties:
      security.protocol: PLAINTEXT
    producer:
      event-processor-mode: tracking
    consumer:
      event-processor-mode: tracking

  axonserver:
    enabled: false
  distributed:
    enabled: true
    spring-cloud:
      fallback-to-http-get: true
      fallback-url: /message-routing-information
      mode: rest
      enable-ignore-listing: true
      enable-accept-all-commands: true
      rest-mode-url: /member-capabilities
  serializer:
    general: xstream
    messages: xstream
    events: jackson

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    metadata-map:
      instance-type: eda
    preferIpAddress: true